name: asr_env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytorch
  - torchaudio
  - pytorch-cuda=12.1
  - ffmpeg
  - pip:
    - faster-whisper==1.0.1
    - kaggle==1.6.6
    - pyyaml==6.0.1
    - tqdm==4.66.2
    - noisereduce==3.0.2
    - librosa==0.10.1